import os

from github import Github, GithubException

_WEBSITE_REPO = "netram75/website"
_BASE_BRANCH = "main"


def _scenario_slug(file_path: str) -> str:
    name = os.path.splitext(os.path.basename(file_path))[0]
    return name.replace("_", "-")


def raise_pr(file_path: str, doc_content: str) -> str:
    token = os.environ.get("GH_TOKEN")
    if not token:
        raise EnvironmentError("GH_TOKEN not set")

    gh = Github(token)
    repo = gh.get_repo(_WEBSITE_REPO)

    slug = _scenario_slug(file_path)
    branch_name = f"docs/auto-{slug}"
    doc_path = f"content/en/docs/network-chaos-ng-scenarios/{slug}/_index.md"

    # create branch off main
    base_sha = repo.get_branch(_BASE_BRANCH).commit.sha
    try:
        repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=base_sha)
    except GithubException as e:
        if e.status == 422:
            # branch already exists — delete and recreate
            repo.get_git_ref(f"heads/{branch_name}").delete()
            repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=base_sha)
        else:
            raise

    # commit the generated doc
    repo.create_file(
        path=doc_path,
        message=f"docs(auto): add {slug} scenario documentation",
        content=doc_content,
        branch=branch_name,
    )

    # open PR
    pr = repo.create_pull(
        title=f"docs(auto): add {slug} scenario documentation",
        body=(
            f"Auto-generated by krkn-docs-sync.\n\n"
            f"Source: `{file_path}`\n\n"
            f"This PR was raised automatically after detecting an undocumented chaos scenario."
        ),
        head=branch_name,
        base=_BASE_BRANCH,
    )

    return pr.html_url
